export const DEFAULT_ISOSURFACE_OPTIONS = Object.freeze({
    useSymmetry: true,
    progressiveSteps: Object.freeze([0.5, 0.75, 1]),
    visible: true,
    sigmaLevel: 3,
    radius: 1.5,
    resolution: 64,
    gridSpacing: 0.15,
    maxResolution: 96,
    stitchTolerance: 1e-4,
    positiveColor: '#267e47',
    negativeColor: '#992a3e',
    deformationPositiveColor: '#4FC3F7',
    deformationNegativeColor: '#FF9800',
    opacity: 0.55,
    wireframe: true,
    maxPolyCount: 100000,
});
