import { CellSymmetry, SymmetryOperation } from '../../cell-symmetry.js';
import { Atom, CrystalStructure } from '../../crystal.js';
import { Bond, HBond } from '../../bonds.js';
import * as math from '../../../math-lite.js';
import { createBondIdentifier, createHBondIdentifier } from './grow-fragment.js';
import { combineAtomId } from './util.js';
import { AppliedSymmetry } from './../../applied-symmetry.js';

const MAX_DISPLAYED_BOND_LENGTH = 4;

/**
 * @typedef {object} FractionalLimits
 * @property {number} minX - Minimum fractional X coordinate.
 * @property {number} maxX - Maximum fractional X coordinate.
 * @property {number} minY - Minimum fractional Y coordinate.
 * @property {number} maxY - Maximum fractional Y coordinate.
 * @property {number} minZ - Minimum fractional Z coordinate.
 * @property {number} maxZ - Maximum fractional Z coordinate.
 */

/**
 * Creates a set of symmetry elements that will fill the complete cell when executed subsequently
 * on the fragment grown from previously grown sets.
 * @param {CellSymmetry} symmetry - Cell symmetry for which the minimal set should be determined
 * @param {string[]} preexistingSymOps - Symmetry elements already generated by growing of fragment
 * @returns {Set<string>} - Set containing the ids of the unique set
 */
export function minimalGrowthSet(symmetry, preexistingSymOps) {
    const keepSet = new Set([symmetry.identitySymOpId]);

    const preexistingSet = new Set();

    // Add all symmetry operations that can be generated from preexisting ones
    for (const existId of preexistingSymOps) {
        const combinedId = symmetry.combineSymmetryCodes(existId + '_555', symmetry.identitySymOpId + '_555');
        preexistingSet.add(combinedId.split('_')[0]);
    }

    // Find minimal set needed to generate all symmetry operations
    for (const [id] of symmetry.operationIds) {
        if (keepSet.has(id) || preexistingSet.has(id)) {
            continue;
        }

        keepSet.add(id);
    }
    return keepSet;
}

/**
 * Calculates the minimum and maximum fractional coordinates for all atoms.
 * @param {Atom[]} atoms - The atoms to analyze
 * @returns {FractionalLimits} An object containing the min/max fractional coordinates
 */
export function getFragmentLimits(atoms) {
    if (atoms.length === 0) {
        return { minX: 0, maxX: 1, minY: 0, maxY: 1, minZ: 0, maxZ: 1 };
    }

    let minX = Infinity, maxX = -Infinity;
    let minY = Infinity, maxY = -Infinity;
    let minZ = Infinity, maxZ = -Infinity;

    for (const atom of atoms) {
        const { x, y, z } = atom.position;
        minX = Math.min(minX, x);
        maxX = Math.max(maxX, x);
        minY = Math.min(minY, y);
        maxY = Math.max(maxY, y);
        minZ = Math.min(minZ, z);
        maxZ = Math.max(maxZ, z);
    }

    return { minX, maxX, minY, maxY, minZ, maxZ };
}

/**
 * Calculates the center of a fragment defined by its atoms.
 * @param {Atom[]} atoms - The atoms defining the fragment
 * @returns {math.Matrix} The center of the fragment as a 3D vector
 */
export function getFragmentCentre(atoms) {
    const limits = getFragmentLimits(atoms);
    return math.matrix([
        (limits.minX + limits.maxX) / 2,
        (limits.minY + limits.maxY) / 2,
        (limits.minZ + limits.maxZ) / 2,
    ]);
}

/**
 * Calculates the symmetry-transformed centre.
 * @param {math.Matrix} centre - Original centre
 * @param {SymmetryOperation} symOp - Symmetry operation
 * @returns {math.Matrix} The symmetry converted center of the fragment as a 3D vector
 */
export function getSymmetryCentre(centre, symOp) {

    const symmCentre = math.add(
        math.multiply(symOp.rotMatrix, centre),
        symOp.transVector,
    );

    return symmCentre;
}

/**
 * Extracts already applied symmetries from atom labels in a group.
 * @param {object} group - Group of atoms
 * @param {CrystalStructure} structure - Crystal structure containing symmetry information
 * @param {Map<string, string>} specialPositionMap - Map of special positions (duplicates
 * @returns {string[]} Array of unique symmetry operation IDs for the group
 */
export function getGrownSymmetriesofGroup(group, structure, specialPositionMap) {
    const identitySymOp = structure.symmetry.identitySymOpId;
    const groupSymmetries = new Set();

    for (const atom of group.atoms) {
        if (atom.appliedSymmetry) {
            groupSymmetries.add(atom.appliedSymmetry.id);
        } else {
            groupSymmetries.add(identitySymOp);
        }
    }

    const atomIdsInGroup = new Set(group.atoms.map(atom => atom.uniqueId));

    for (const [originalId, mapTargetId] of specialPositionMap) {
        let symOpId = identitySymOp;
        // Parse ID directly since it's now guaranteed to be label|symmetry
        // Format: Label|SymID_Trans
        if (originalId.includes('|')) {
            const symKey = originalId.split('|')[1];
            symOpId = symKey.split('_')[0];
        }

        if (atomIdsInGroup.has(mapTargetId)) {
            groupSymmetries.add(symOpId);
        }
    }

    return Array.from(groupSymmetries);
}

/**
 * Checks if an atom position is within the unit cell.
 *
 * The upper bound is the packing cutoff: with the default 1.0 an atom sitting on
 * the far face (fractional 1.0) is treated as the same periodic position as 0.0 and
 * wrapped in, which keeps the cell contents (Z) correct. Raising it slightly (e.g.
 * 1.001) instead keeps those upper-border atoms, giving a "closed" packing diagram
 * at the cost of duplicating face/edge/corner atoms.
 * @param {Atom} atom - Atom to check
 * @param {number} [cutoff] - Upper fractional bound (packing cutoff)
 * @param {number} [tolerance] - Tolerance for boundary comparisons
 * @returns {boolean} True if atom is within unit cell
 */
function isWithinUnitCell(atom, cutoff = 1, tolerance = 1e-6) {
    const { x, y, z } = atom.position;
    // Atoms at position >= cutoff - tolerance are wrapped to the same periodic
    // position one cell lower.
    return x >= -tolerance && x < cutoff - tolerance &&
        y >= -tolerance && y < cutoff - tolerance &&
        z >= -tolerance && z < cutoff - tolerance;
}

/**
 * Creates a unique key for atom position to detect duplicates/special positions.
 * @param {Atom} atom - Atom to create key for
 * @param {number} [precision] - Decimal places for rounding
 * @returns {string} Position key
 */
function getAtomPositionKey(atom, precision = 3) {
    // Use toFixed for consistent string representation to avoid floating-point precision issues
    // (e.g., 0.14485 and 0.14484999999999992 should produce the same key)
    const x = atom.position.x.toFixed(precision);
    const y = atom.position.y.toFixed(precision);
    const z = atom.position.z.toFixed(precision);
    // Use the base chemical label from the atom, which is now just 'label'
    return `${atom.label}_x${x}_y${y}_z${z}`;
}

/**
 * Transforms a symmetry string to center it around a given symmetry centre.
 * @param {CellSymmetry} symmetry - Cell symmetry object
 * @param {string} symmString - Symmetry string to transform
 * @param {object} symmCentre - Centre coordinates to center the symmetry string around
 * @returns {string} Transformed symmetry string
 */
export function centreSymmetryString(symmetry, symmString, symmCentre) {
    const { symOp, transVector } = symmetry.parsePositionCode(symmString);

    const symOpResult = math.add(
        math.multiply(symOp.rotMatrix, math.matrix(symmCentre)),
        symOp.transVector,
    );

    const transformedCentre = math.add(symOpResult, transVector);

    const offsetX = Math.floor(transformedCentre.get([0]));
    const offsetY = Math.floor(transformedCentre.get([1]));
    const offsetZ = Math.floor(transformedCentre.get([2]));

    const originalSymmetry = symmString.split('_')[0];

    const originalTranslationString = symmString.split('_')[1] || '555';
    const translationParts = originalTranslationString.split('').map(part => {
        return parseInt(part, 10); // Default to 5 if part is not a number
    });

    const newTranslationString = (
        `${translationParts[0] - offsetX}`
        + `${translationParts[1] - offsetY}`
        + `${translationParts[2] - offsetZ}`
    );

    const offsetCentre = math.subtract(transformedCentre, math.matrix([offsetX, offsetY, offsetZ]));
    return { newCentre: offsetCentre, newString: `${originalSymmetry}_${newTranslationString}` };
}

/**
 * @typedef {object} CreatedObjectTracker
 * @property {Map<string, string>} atomMap - Maps atom position keys to atom labels
 * @property {Set<string>} createdBonds - Set of created bond identifiers
 * @property {Set<string>} createdHBonds - Set of created hydrogen bond identifiers
 * @property {Map<string, string>} specialPositionMap - Maps original atom labels to kept atom labels for duplicates
 * @property {Map<string, string[]>} atomTranslations - Maps original atom labels to [new label,
 *  translation string]
 */

/**
 * @typedef {object} GrownGroup
 * @property {Atom[]} atoms - Atoms in the group
 * @property {Bond[]} internalBonds - Bonds in the group
 * @property {HBond[]} internalHBonds - Hydrogen bonds in the group
 * @property {Bond[]} externalBonds - External bonds to atoms outside the group
 * @property {HBond[]} externalHBonds - External hydrogen bonds to atoms outside the group
 * @property {string} symmString - Symmetry string for the group
 * @property {string} groupCentre - Original center of the group (includes ommitted special position atoms)
 */

/**
 * Grows atoms in a group with the given symmetry and symmetry string.
 * This function applies the symmetry operations to the atoms in the group,
 * updates their labels, and checks for duplicates/special positions. It also
 * updates the object tracker to keep track of created atoms and translations.
 * @param {GrownGroup} grownGroup - The group of atoms to grow
 * @param {CellSymmetry} symmetry - The symmetry object containing symmetry operations
 * @param {string} symmString - The symmetry string to grow the atoms with
 * @param {CreatedObjectTracker} objectTracker - Object tracker to keep track of created atoms. Used
 *  to avoid duplicates and track translations, as well as special positions.
 * @param {boolean} moveAtomsInsideCell - Whether to move atoms inside the unit cell
 * @param {number} [packingCutoff] - Upper fractional bound for cell membership (see isWithinUnitCell)
 * @returns {GrownGroup} New group with grown atoms and updated symmetry string
 */
export function growAtomsinGroup(
    grownGroup, symmetry, symmString, objectTracker, moveAtomsInsideCell, packingCutoff = 1,
) {
    const newAtoms = [];
    const transformedAtoms = symmetry.applySymmetry(symmString, grownGroup.atoms);

    // Process transformed atoms
    for (let i = 0; i < transformedAtoms.length; i++) {
        const atom = transformedAtoms[i];
        const originalAtom = grownGroup.atoms[i];

        // If original atom had an existing symmetry (from fragment growth), combine with new symmetry
        // Otherwise just use the new symmetry
        let combinedSymm = symmString;
        if (originalAtom.appliedSymmetry && originalAtom.appliedSymmetry.key !== `${symmetry.identitySymOpId}_555`) {
            // Combine: new symmetry (outer) applied to existing symmetry (inner)
            combinedSymm = symmetry.combineSymmetryCodes(symmString, originalAtom.appliedSymmetry.key);
        }

        // Atom label remains the chemical label (e.g., C1)
        // We track combined symmetry via appliedSymmetry object
        atom.appliedSymmetry = AppliedSymmetry.fromString(combinedSymm);
        const preShiftId = atom.uniqueId;

        // Check if atom is within unit cell
        if (moveAtomsInsideCell && !isWithinUnitCell(atom, packingCutoff)) {
            const atomOffsetX = Math.floor(atom.position.x);
            const atomOffsetY = Math.floor(atom.position.y);
            const atomOffsetZ = Math.floor(atom.position.z);
            atom.position.x -= atomOffsetX;
            atom.position.y -= atomOffsetY;
            atom.position.z -= atomOffsetZ;

            // Update symmetry translation
            atom.appliedSymmetry.translation[0] -= atomOffsetX;
            atom.appliedSymmetry.translation[1] -= atomOffsetY;
            atom.appliedSymmetry.translation[2] -= atomOffsetZ;
            atom.appliedSymmetry._updateKey(); // Important: update key after modifying

            const postShiftId = atom.uniqueId;
            const translationString = `${symmetry.identitySymOpId}_`
                + `${5 - atomOffsetX}${5 - atomOffsetY}${5 - atomOffsetZ}`;

            // Map the pre-shift ID (which internal bonds will look for) to the final post-shift ID
            objectTracker.atomTranslations.set(preShiftId, [postShiftId, translationString]);
        }

        const uniqueId = atom.uniqueId;

        // Check for special positions (duplicates)
        const posKey = getAtomPositionKey(atom);
        const existingAtomId = objectTracker.atomMap.get(posKey);

        if (existingAtomId) {
            // This is a special position - map to existing atom ID
            objectTracker.specialPositionMap.set(uniqueId, existingAtomId);
        } else {
            // New unique position
            objectTracker.atomMap.set(posKey, uniqueId);
            newAtoms.push(atom);
        }
    }
    return newAtoms;
}

/**
 * Grows internal bonds in a group of atoms, with the symmetry string provided. 
 * Will check for already created bonds and avoid duplicates. Will also update
 * the object tracker to keep track of created bonds.
 * @param {GrownGroup} grownGroup - The group of atoms with internal bonds to grow
 * @param {CellSymmetry} symmetry - The symmetry object used to combine symmetry codes
 * @param {string} symmString - The symmetry string to use for growing the bonds
 * @param {CreatedObjectTracker} objectTracker - Object tracker to keep track of created bonds and atom translations.
 *  The function will update the object tracker with new bond IDs.
 * @returns {Bond[]} Grown bonds from the group
 */
export function growInternalBondsInGroup(grownGroup, symmetry, symmString, objectTracker) {
    const grownBonds = [];
    for (const bond of grownGroup.internalBonds) {
        const potentialAtom1Id = combineAtomId(bond.atom1Id, symmString, symmetry);
        const atom1Id = objectTracker.specialPositionMap.get(potentialAtom1Id) || potentialAtom1Id;
        const potentialAtom2Id = combineAtomId(bond.atom2Id, symmString, symmetry);
        const atom2Id = objectTracker.specialPositionMap.get(potentialAtom2Id) || potentialAtom2Id;

        // Skip self-bonds
        if (atom1Id === atom2Id) {
            continue;
        }

        if (!objectTracker.atomTranslations.has(atom1Id) && !objectTracker.atomTranslations.has(atom2Id)) {
            // If both atoms are not translated, use their original IDs

            const bondId = createBondIdentifier(atom1Id, atom2Id);
            if (!objectTracker.createdBonds.has(bondId)) {
                // Note: We use atom1Id/atom2Id which are now IDs (Label|Symmetry)
                const newBond = new Bond(
                    atom1Id,
                    atom2Id,
                    bond.bondLength,
                    bond.bondLengthSU,
                    '.',
                );
                grownBonds.push(newBond);
                objectTracker.createdBonds.add(bondId);
            }
        } else if (objectTracker.atomTranslations.has(atom1Id) && objectTracker.atomTranslations.has(atom2Id)) {
            // If both atoms are translated, use their new IDs
            const [newAtom1Id, symm1] = objectTracker.atomTranslations.get(atom1Id);
            const [newAtom2Id, symm2] = objectTracker.atomTranslations.get(atom2Id);

            if (symm1 === symm2) {
                // Only create bond if atoms have been translated with the same symmetry
                const bondId = createBondIdentifier(newAtom1Id, newAtom2Id);
                if (!objectTracker.createdBonds.has(bondId)) {
                    const newBond = new Bond(
                        newAtom1Id,
                        newAtom2Id,
                        bond.bondLength,
                        bond.bondLengthSU,
                        '.',
                    );
                    grownBonds.push(newBond);
                    objectTracker.createdBonds.add(bondId);
                }
            }
        }
        // if only one atom is translated, we skip the bond (bond crosses cell boundary)
    }
    return grownBonds;
}

/**
 * Grows hydrogen bonds in a group of atoms, with the symmetry string provided.
 * Will check for already created hydrogen bonds and avoid duplicates. Will also update
 * the object tracker to keep track of created hydrogen bonds.
 * @param {GrownGroup} grownGroup - The group of atoms with hydrogen bonds to grow
 * @param {CellSymmetry} symmetry - The symmetry object used to combine symmetry codes
 * @param {string} symmString - The symmetry string to use for growing the group
 * @param {CreatedObjectTracker} objectTracker - Object tracker to keep track of created hydrogen bonds and atom 
 *  translations. The function will update the object tracker with new hydrogen bond IDs.
 * @returns {HBond[]} Grown hydrogen bonds from the group
 */
export function growInternalHBondsInGroup(grownGroup, symmetry, symmString, objectTracker) {
    const grownHBonds = [];

    for (const hbond of grownGroup.internalHBonds) {
        const donorId = objectTracker.specialPositionMap.get(
            combineAtomId(hbond.donorAtomId, symmString, symmetry),
        ) || combineAtomId(hbond.donorAtomId, symmString, symmetry);

        const hydrogenId = objectTracker.specialPositionMap.get(
            combineAtomId(hbond.hydrogenAtomId, symmString, symmetry),
        ) || combineAtomId(hbond.hydrogenAtomId, symmString, symmetry);

        // For external H-bonds (acceptorAtomSymmetry !== '.'), combine the acceptor's symmetry
        // with the new group symmetry, then extract base label and combine
        let acceptorId;
        if (hbond.acceptorAtomSymmetry && hbond.acceptorAtomSymmetry !== '.') {
            // External H-bond: combine symmetries and use base label
            const acceptorBaseLabel = hbond.acceptorAtomId.split('|')[0];
            const combinedAcceptorSymm = symmetry.combineSymmetryCodes(symmString, hbond.acceptorAtomSymmetry);
            const potentialAcceptorId = `${acceptorBaseLabel}|${combinedAcceptorSymm}`;
            acceptorId = objectTracker.specialPositionMap.get(potentialAcceptorId) || potentialAcceptorId;
        } else {
            // Internal H-bond: just combine with group symmetry
            acceptorId = objectTracker.specialPositionMap.get(
                combineAtomId(hbond.acceptorAtomId, symmString, symmetry),
            ) || combineAtomId(hbond.acceptorAtomId, symmString, symmetry);
        }

        if (
            !objectTracker.atomTranslations.has(donorId)
            && !objectTracker.atomTranslations.has(hydrogenId)
            && !objectTracker.atomTranslations.has(acceptorId)
        ) {
            const hbondId = createHBondIdentifier(donorId, hydrogenId, acceptorId);
            if (!objectTracker.createdHBonds.has(hbondId)) {
                const newHBond = new HBond(
                    donorId,
                    hydrogenId,
                    acceptorId,
                    hbond.donorHydrogenDistance,
                    hbond.donorHydrogenDistanceSU,
                    hbond.acceptorHydrogenDistance,
                    hbond.acceptorHydrogenDistanceSU,
                    hbond.donorAcceptorDistance,
                    hbond.donorAcceptorDistanceSU,
                    hbond.hBondAngle,
                    hbond.hBondAngleSU,
                    '.',
                );
                objectTracker.createdHBonds.add(hbondId);
                grownHBonds.push(newHBond);
            }
        } else if (
            objectTracker.atomTranslations.has(donorId) &&
            objectTracker.atomTranslations.has(hydrogenId) &&
            objectTracker.atomTranslations.has(acceptorId)
        ) {
            // If all atoms are translated, use their new labels
            const [newDonorId, symmD] = objectTracker.atomTranslations.get(donorId);
            const [newHydrogenId, symmH] = objectTracker.atomTranslations.get(hydrogenId);
            const [newAcceptorId, symmA] = objectTracker.atomTranslations.get(acceptorId);

            if (symmD === symmH && symmH === symmA) {

                const hbondId = createHBondIdentifier(newDonorId, newHydrogenId, newAcceptorId);
                if (!objectTracker.createdHBonds.has(hbondId)) {
                    const newHBond = new HBond(
                        newDonorId,
                        newHydrogenId,
                        newAcceptorId,
                        hbond.donorHydrogenDistance,
                        hbond.donorHydrogenDistanceSU,
                        hbond.acceptorHydrogenDistance,
                        hbond.acceptorHydrogenDistanceSU,
                        hbond.donorAcceptorDistance,
                        hbond.donorAcceptorDistanceSU,
                        hbond.hBondAngle,
                        hbond.hBondAngleSU,
                        '.',
                    );
                    objectTracker.createdHBonds.add(hbondId);
                    grownHBonds.push(newHBond);
                }
            }
        }
        // if only part of the atoms are translated, we skip the H-bond
    }
    return grownHBonds;
}

/**
 *  Grows external bonds in a group of atoms, with the symmetry string provided.
 *  Will check for already created bonds and avoid duplicates. Will also update
 *  the object tracker to keep track of created bonds.
 * @param {GrownGroup} grownGroup - The group of atoms with external bonds to
 *  grow
 * @param {CellSymmetry} symmetry - The symmetry object used to combine symmetry codes
 * @param {string} symmString - The symmetry string to use for growing the group/bonds
 * @param {CreatedObjectTracker} objectTracker - Object tracker to keep track of created bonds.
 *  The function will update the object tracker with new bond IDs.
 * @returns {Bond[]} Grown external bonds from the group
 */
export function growExternalBondsInGroup(grownGroup, symmetry, symmString, objectTracker) {
    const grownExternalBonds = [];
    for (const bond of grownGroup.externalBonds) {
        let atom1Id = objectTracker.specialPositionMap.get(
            combineAtomId(bond.atom1Id, symmString, symmetry),
        ) || combineAtomId(bond.atom1Id, symmString, symmetry);

        let atom2Symm = symmetry.combineSymmetryCodes(
            symmString,
            bond.atom2SiteSymmetry,
        );
        const atom2BaseLabel = bond.atom2Id.split('|')[0];

        if (objectTracker.atomTranslations.has(atom1Id)) {
            let atom1Symm;
            [atom1Id, atom1Symm] = objectTracker.atomTranslations.get(atom1Id);
            // Re-calculate atom2Symm based on the translation of atom1?
            // If atom1 was translated, its effective symmetry changed.
            // We need to apply that same "shift" logic to atom2Symm?
            // Or rather, combine symmetry codes properly.

            // logic in original code:
            // atom2Symm = symmetry.combineSymmetryCodes(atom1Symm, atom2Symm);
            // This looks suspicious. atom1Symm is the translation string e.g. "1_565".
            // If we combine it with atom2Symm, we are shifting atom2Symm too.
            // This seems correct if the relative symmetry is preserved.

            atom2Symm = symmetry.combineSymmetryCodes(
                atom1Symm,
                atom2Symm,
            );
        }

        let atom2Id = `${atom2BaseLabel}|${atom2Symm}`;
        atom2Id = objectTracker.specialPositionMap.get(atom2Id) || atom2Id;

        const bondId = createBondIdentifier(atom1Id, atom2Id);
        if (!objectTracker.createdBonds.has(bondId)) {

            const newBond = new Bond(
                atom1Id,
                atom2Id, // Use calculated atom2Id with combined symmetry
                bond.bondLength,
                bond.bondLengthSU,
                atom2Symm,
            );

            grownExternalBonds.push(newBond);
            objectTracker.createdBonds.add(bondId);
        }
    }
    return grownExternalBonds;
}

/**
 * Grows external hydrogen bonds in a group of atoms, with the symmetry string provided.
 * Will check for already created hydrogen bonds and avoid duplicates. Will also update
 * the object tracker to keep track of created hydrogen bonds.
 * @param {GrownGroup} grownGroup - The group of atoms with hydrogen bonds to grow
 * @param {CellSymmetry} symmetry - The symmetry object used to combine symmetry codes
 * @param {string} symmString - The symmetry string to use for growing the group
 * @param {CreatedObjectTracker} objectTracker - Object tracker to keep track of created hydrogen bonds and atom
 * translations. The function will update the object tracker with new hydrogen bond IDs.
 * @returns {HBond[]} Grown external hydrogen bonds from the group
 */
export function growExternalHBondsInGroup(grownGroup, symmetry, symmString, objectTracker) {
    const grownExternalHBonds = [];
    for (const hBond of grownGroup.externalHBonds) {
        let donorId = objectTracker.specialPositionMap.get(
            combineAtomId(hBond.donorAtomId, symmString, symmetry),
        ) || combineAtomId(hBond.donorAtomId, symmString, symmetry);

        let hydrogenId = objectTracker.specialPositionMap.get(
            combineAtomId(hBond.hydrogenAtomId, symmString, symmetry),
        ) || combineAtomId(hBond.hydrogenAtomId, symmString, symmetry);

        let acceptorSymm = symmetry.combineSymmetryCodes(
            symmString,
            hBond.acceptorAtomSymmetry,
        );

        // Don't calculate acceptorId yet - it depends on acceptorSymm which may be modified below

        if (
            objectTracker.atomTranslations.has(donorId)
            && objectTracker.atomTranslations.has(hydrogenId)
        ) {
            let donorTransSymm;
            [donorId, donorTransSymm] = objectTracker.atomTranslations.get(donorId);
            const [hydrogenIdr, hydrogenSymm] = objectTracker.atomTranslations.get(hydrogenId);
            if (donorTransSymm !== hydrogenSymm) {
                continue;
            }
            hydrogenId = hydrogenIdr;
            acceptorSymm = symmetry.combineSymmetryCodes(
                donorTransSymm,
                acceptorSymm,
            );
        } else if (
            objectTracker.atomTranslations.has(donorId)
            || objectTracker.atomTranslations.has(hydrogenId)
        ) {
            // If only one atom is translated, we skip the hydrogen bond
            continue;
        }

        // Now calculate acceptorId with the corrected acceptorSymm
        // Extract base label from acceptorAtomId (may already contain symmetry)
        const acceptorBaseLabel = hBond.acceptorAtomId.split('|')[0];
        const acceptorId = `${acceptorBaseLabel}|${acceptorSymm}`;

        // Skip intra-molecular H-bonds: if donor and acceptor are in the same molecule after
        // symmetry combination, this is not a valid inter-molecular H-bond
        // The donor's symmetry after this growth is embedded in donorId as the part after '|'
        const donorSymm = donorId.split('|')[1];
        if (donorSymm === acceptorSymm) {
            // Donor and acceptor are in the same molecule - skip this H-bond
            continue;
        }

        const hbondId = createHBondIdentifier(donorId, hydrogenId, acceptorId);
        if (!objectTracker.createdHBonds.has(hbondId)) {
            const newHBond = new HBond(
                donorId,
                hydrogenId,
                acceptorId, // Use calculated acceptorId with combined symmetry
                hBond.donorHydrogenDistance,
                hBond.donorHydrogenDistanceSU,
                hBond.acceptorHydrogenDistance,
                hBond.acceptorHydrogenDistanceSU,
                hBond.donorAcceptorDistance,
                hBond.donorAcceptorDistanceSU,
                hBond.hBondAngle,
                hBond.hBondAngleSU,
                acceptorSymm,
            );

            grownExternalHBonds.push(newHBond);
            objectTracker.createdHBonds.add(hbondId);
        }
    }
    return grownExternalHBonds;
}

/** 
 * Grows a group of atoms with the given symmetry and symmetry string.
 * This function applies the symmetry operations to the atoms in the group,
 * grows internal and external bonds, and returns a new group with the grown atoms and bonds.
 * @param {GrownGroup} grownGroup - The group of atoms to grow
 * @param {CellSymmetry} symmetry - The symmetry object containing symmetry operations
 * @param {string} symmString - The symmetry string to use for the group
 * @param {CreatedObjectTracker} objectTracker - Object tracker to keep track of created atoms and bonds
 * @param {boolean} moveAtomsInsideCell - Whether to move atoms inside the unit cell
 * @param {number} [packingCutoff] - Upper fractional bound for cell membership (see isWithinUnitCell)
 * @returns {GrownGroup} New group with grown atoms, internal and external bonds, and symmetry string
 */
export function growGroup(
    grownGroup, symmetry, symmString, objectTracker, moveAtomsInsideCell, packingCutoff = 1,
) {
    const combinedSymmString = symmetry.combineSymmetryCodes(
        symmString,
        grownGroup.symmString,
    );

    const { newCentre: transformedCentre, newString: centredSymmString } = centreSymmetryString(
        symmetry,
        combinedSymmString,
        grownGroup.groupCentre,
    );

    const grownAtoms = growAtomsinGroup(
        grownGroup,
        symmetry,
        centredSymmString,
        objectTracker,
        moveAtomsInsideCell,
        packingCutoff,
    );

    const grownInternalBonds = growInternalBondsInGroup(
        grownGroup,
        symmetry,
        centredSymmString,
        objectTracker,
    );

    const grownInternalHBonds = growInternalHBondsInGroup(
        grownGroup,
        symmetry,
        centredSymmString,
        objectTracker,
    );

    const grownExternalBonds = growExternalBondsInGroup(
        grownGroup,
        symmetry,
        centredSymmString,
        objectTracker,
    );

    const grownExternalHBonds = growExternalHBondsInGroup(
        grownGroup,
        symmetry,
        centredSymmString,
        objectTracker,
    );

    return {
        atoms: grownAtoms,
        internalBonds: grownInternalBonds,
        internalHBonds: grownInternalHBonds,
        externalBonds: grownExternalBonds,
        externalHBonds: grownExternalHBonds,
        symmString: centredSymmString,
        groupCentre: transformedCentre,
    };

}

/**
 * Grows a crystal structure to fill a complete unit cell.
 * @param {CrystalStructure} structure - Input crystal structure
 * @param {boolean} [moveAtomsInsideCell] - Whether to exclude atoms outside unit cell
 * @param {Map<string,string>} [startingSpecialPositions] - Optional special positions map to start with.
 * @param {number} [packingCutoff] - Upper fractional bound for cell membership. 1.0 (default) wraps
 *  far-face atoms in for a correct Z; a slightly larger value (e.g. 1.001) keeps upper-border atoms.
 * @returns {CrystalStructure} New structure filling the unit cell
 */
export function growCell(
    structure, moveAtomsInsideCell = true, startingSpecialPositions = null, packingCutoff = 1,
) {
    let specialPositionMap;
    if (startingSpecialPositions !== null) {
        // If a starting special position is provided, initialize the map with it
        specialPositionMap = startingSpecialPositions;
    } else {
        specialPositionMap = new Map(); // duplicate label -> kept label
    }

    // Early return for empty structures
    if (structure.atoms.length === 0) {
        return new CrystalStructure(
            structure.cell,
            [],
            [],
            [],
            structure.symmetry,
        );
    }

    // Analyze connected groups and their symmetry operations
    const atomGroups = structure.calculateConnectedGroups();

    // Determine minimal set of symmetry operations needed for each group
    const growSymIdsPerGroup = atomGroups.map(group => {
        const alreadyGrownSymmetries = getGrownSymmetriesofGroup(
            group,
            structure,
            specialPositionMap,
        );
        return Array.from(minimalGrowthSet(structure.symmetry, alreadyGrownSymmetries));
    });

    const groupsExternalBonds = atomGroups.map(group => {
        return structure.bonds.filter(bond =>
            (bond.atom2SiteSymmetry && bond.atom2SiteSymmetry !== '.') &&
            // Extract base label from atom1Label (e.g., 'N|1_555' -> 'N') for comparison
            group.atoms.some(atom => atom.label === bond.atom1Id.split('|')[0]),
        );
    });

    const groupsExternalHBonds = atomGroups.map(group => {
        return structure.hBonds.filter(hbond =>
            (hbond.acceptorAtomSymmetry && hbond.acceptorAtomSymmetry !== '.') &&
            // Extract base label from donorAtomLabel (e.g., 'N|1_555' -> 'N') for comparison
            group.atoms.some(atom => atom.label === hbond.donorAtomId.split('|')[0]),
        );
    });

    // Prepare collections for the grown structure. All final atoms come from the
    // centred groups below, so duplicate detection must not be pre-seeded with
    // uncentred input atoms that will not be retained.
    const atomMap = new Map();

    const objectTracker = {
        atomMap,
        createdBonds: new Set(), // createdBonds
        createdHBonds: new Set(), // createdHBonds
        specialPositionMap, // specialPositionMap
        atomTranslations: new Map(), // atomTranslations
    };

    const grownAtomsGroups = new Array();

    // Process each atom group with its required symmetry operations
    for (let groupIdx = 0; groupIdx < atomGroups.length; groupIdx++) {
        const group = atomGroups[groupIdx];
        const symOpsToApply = growSymIdsPerGroup[groupIdx];
        // Each disconnected molecule/component must choose its own lattice
        // translation. Using the centre of the entire asymmetric unit moves all
        // components as one object and can leave some of them outside the cell.
        const originalCentre = getFragmentCentre(group.atoms);

        const symId = symOpsToApply[0];

        const baseGrownGroup = {
            atoms: group.atoms,
            internalBonds: group.bonds,
            internalHBonds: group.hBonds,
            symmString: `${symId}_555`, // Use the first symmetry operation with a placeholder
            groupCentre: originalCentre,
            externalBonds: groupsExternalBonds[groupIdx],
            externalHBonds: groupsExternalHBonds[groupIdx],
        };

        for (const symId of symOpsToApply) {

            const nonTransSymmString = `${symId}_555`;
            // Grow the group with the new symmetry operation
            const newGrownGroup = growGroup(
                baseGrownGroup,
                structure.symmetry,
                nonTransSymmString,
                objectTracker,
                moveAtomsInsideCell,
                packingCutoff,
            );
            grownAtomsGroups.push(newGrownGroup);
        }
    }
    // Preserve the fragment-grown objects in fragment-cell mode so their bond and
    // H-bond endpoint IDs remain available. The post-filter component pass below
    // centres and deduplicates both these objects and the newly grown copies.
    const clonedInputAtoms = !moveAtomsInsideCell
        ? structure.symmetry.applySymmetry(
            `${structure.symmetry.identitySymOpId}_555`,
            structure.atoms,
        ).map((atom, index) => {
            atom.appliedSymmetry = structure.atoms[index].appliedSymmetry?.copy() || null;
            return atom;
        })
        : [];
    const candidateAtoms = [
        ...clonedInputAtoms,
        ...grownAtomsGroups.flatMap(group => group.atoms),
    ];
    const finalAtomsByUniqueId = new Map();
    for (const atom of candidateAtoms) {
        if (!finalAtomsByUniqueId.has(atom.uniqueId)) {
            finalAtomsByUniqueId.set(atom.uniqueId, atom);
        }
    }
    const finalAtoms = Array.from(finalAtomsByUniqueId.values());
    const finalBonds = [
        ...(!moveAtomsInsideCell ? structure.bonds.map(bond => new Bond(
            bond.atom1Id,
            bond.atom2Id,
            bond.bondLength,
            bond.bondLengthSU,
            bond.atom2SiteSymmetry,
        )) : []),
        ...grownAtomsGroups.flatMap(group => group.internalBonds),
    ];
    const finalHBonds = [
        ...(!moveAtomsInsideCell ? structure.hBonds.map(hbond => new HBond(
            hbond.donorAtomId,
            hbond.hydrogenAtomId,
            hbond.acceptorAtomId,
            hbond.donorHydrogenDistance,
            hbond.donorHydrogenDistanceSU,
            hbond.acceptorHydrogenDistance,
            hbond.acceptorHydrogenDistanceSU,
            hbond.donorAcceptorDistance,
            hbond.donorAcceptorDistanceSU,
            hbond.hBondAngle,
            hbond.hBondAngleSU,
            hbond.acceptorAtomSymmetry,
        )) : []),
        ...grownAtomsGroups.flatMap(group => group.internalHBonds),
    ];
    const finalAtomLabels = new Set(finalAtoms.map(atom => atom.uniqueId));

    grownAtomsGroups.forEach(group => {
        // Add external bonds and H-bonds to the potential maps
        group.externalBonds.forEach(bond => {
            // Resolve atom1Id through translations and special positions
            let atom1Id = objectTracker.specialPositionMap.get(bond.atom1Id) || bond.atom1Id;
            if (objectTracker.atomTranslations.has(atom1Id)) {
                [atom1Id] = objectTracker.atomTranslations.get(atom1Id);
            }

            // growExternalBondsInGroup has already combined the group's symmetry with
            // atom2SiteSymmetry. Recombining here applies the operation twice and can
            // connect an atom to the wrong periodic image across the entire cell.
            let atom2Id = objectTracker.specialPositionMap.get(bond.atom2Id) || bond.atom2Id;
            if (objectTracker.atomTranslations.has(atom2Id)) {
                [atom2Id] = objectTracker.atomTranslations.get(atom2Id);
            }
            // Do NOT normalize to _555 - atoms at different translations are different positions

            // For external bonds, only create if both atoms exist and are not at same position
            if (finalAtomLabels.has(atom1Id) && finalAtomLabels.has(atom2Id) && atom1Id !== atom2Id) {
                // Both atoms exist in the grown structure -> create non-symm Bond
                const newBond = new Bond(
                    atom1Id,
                    atom2Id,
                    bond.bondLength,
                    bond.bondLengthSU,
                    '.',
                );
                finalBonds.push(newBond);
            } else if (finalAtomLabels.has(atom1Id)) {
                // Only atom1 exists in the grown structure -> create symm Bond
                const newBond = new Bond(
                    atom1Id,
                    bond.atom2Id,
                    bond.bondLength,
                    bond.bondLengthSU,
                    bond.atom2SiteSymmetry,
                );
                finalBonds.push(newBond);
            }

        });

        group.externalHBonds.forEach(hbond => {
            let donorTranslation = null;
            let donorLookup = objectTracker.specialPositionMap.get(hbond.donorAtomId) || hbond.donorAtomId;
            if (!finalAtomLabels.has(donorLookup)) {
                donorLookup = objectTracker.specialPositionMap.get(donorLookup) || donorLookup;
                if (objectTracker.atomTranslations.has(donorLookup)) {
                    [donorLookup, donorTranslation] = objectTracker.atomTranslations.get(donorLookup);
                }
            }
            let hydrogenTranslation = null;
            let hydrogenLookup = objectTracker.specialPositionMap.get(
                hbond.hydrogenAtomId,
            ) || hbond.hydrogenAtomId;
            if (!finalAtomLabels.has(hydrogenLookup)) {
                hydrogenLookup = objectTracker.specialPositionMap.get(hydrogenLookup) || hydrogenLookup;
                if (objectTracker.atomTranslations.has(hydrogenLookup)) {
                    [hydrogenLookup, hydrogenTranslation] = objectTracker.atomTranslations.get(hydrogenLookup);
                }
            }
            // Determine acceptor lookup - if acceptorAtomSymmetry is '.' or undefined, use acceptorAtomLabel directly
            // Otherwise, combine base label with symmetry
            let acceptorLookup;
            if (!hbond.acceptorAtomSymmetry || hbond.acceptorAtomSymmetry === '.') {
                // Internal H-bond or already resolved - use acceptorAtomLabel (which is same as acceptorAtomId)
                acceptorLookup = hbond.acceptorAtomId;
            } else {
                // External H-bond - combine base label with symmetry
                const acceptorBaseLabel = hbond.acceptorAtomId.split('|')[0];
                acceptorLookup = `${acceptorBaseLabel}|${hbond.acceptorAtomSymmetry}`;
            }

            if (!finalAtomLabels.has(acceptorLookup)) {
                acceptorLookup = objectTracker.specialPositionMap.get(acceptorLookup) || acceptorLookup;
                if (objectTracker.atomTranslations.has(acceptorLookup)) {
                    const [translatedAcceptor, acceptorTranslation] = objectTracker.atomTranslations.get(
                        acceptorLookup,
                    );
                    // Wrapping only the acceptor changes the periodic image in the H-bond. Internalize it only
                    // when donor, hydrogen, and acceptor were all wrapped by the same lattice translation.
                    if (donorTranslation === acceptorTranslation &&
                        hydrogenTranslation === acceptorTranslation) {
                        acceptorLookup = translatedAcceptor;
                    }
                }
            }

            if (
                finalAtomLabels.has(donorLookup) &&
                finalAtomLabels.has(hydrogenLookup) &&
                finalAtomLabels.has(acceptorLookup)
            ) {
                // All atoms exist in the grown structure -> create non-symm HBond
                const newHBond = new HBond(
                    donorLookup,
                    hydrogenLookup,
                    acceptorLookup,
                    hbond.donorHydrogenDistance,
                    hbond.donorHydrogenDistanceSU,
                    hbond.acceptorHydrogenDistance,
                    hbond.acceptorHydrogenDistanceSU,
                    hbond.donorAcceptorDistance,
                    hbond.donorAcceptorDistanceSU,
                    hbond.hBondAngle,
                    hbond.hBondAngleSU,
                    '.',
                );
                finalHBonds.push(newHBond);
            } else if (
                finalAtomLabels.has(donorLookup) &&
                finalAtomLabels.has(hydrogenLookup)
            ) {
                // Only donor and hydrogen exist in the grown structure -> create symm HBond
                const newHBond = new HBond(
                    donorLookup,
                    hydrogenLookup,
                    hbond.acceptorAtomId,
                    hbond.donorHydrogenDistance,
                    hbond.donorHydrogenDistanceSU,
                    hbond.acceptorHydrogenDistance,
                    hbond.acceptorHydrogenDistanceSU,
                    hbond.donorAcceptorDistance,
                    hbond.donorAcceptorDistanceSU,
                    hbond.hBondAngle,
                    hbond.hBondAngleSU,
                    hbond.acceptorAtomSymmetry,
                );
                finalHBonds.push(newHBond);
            }
        });
    });

    const finalAtomsById = new Map(finalAtoms.map(atom => [atom.uniqueId, atom]));
    const cartesianPositions = new Map();

    const getCartesianPosition = atom => {
        let position = cartesianPositions.get(atom.uniqueId);
        if (!position) {
            position = atom.position.toCartesian(structure.cell);
            cartesianPositions.set(atom.uniqueId, position);
        }
        return position;
    };

    /**
     * Checks that a displayed internal bond still connects nearby periodic images.
     * @param {Bond} bond - Bond to check
     * @returns {boolean} Whether the bond length is compatible with its CIF value
     */
    const hasCompatibleDisplayedLength = bond => {
        if (!Number.isFinite(bond.bondLength)) {
            return true;
        }
        // _geom_bond loops frequently include long publication contacts in addition
        // to chemical bonds. They are useful metadata but should not become solid
        // lines spanning a cell visualization.
        if (bond.bondLength > MAX_DISPLAYED_BOND_LENGTH) {
            return false;
        }
        const atom1 = finalAtomsById.get(bond.atom1Id);
        const atom2 = finalAtomsById.get(bond.atom2Id);
        if (!atom1 || !atom2) {
            // Preserve unresolved external bond metadata. Rendering already omits it
            // because both displayed endpoints are required.
            return bond.atom2SiteSymmetry && bond.atom2SiteSymmetry !== '.';
        }
        const cart1 = getCartesianPosition(atom1);
        const cart2 = getCartesianPosition(atom2);
        const actualLength = Math.hypot(
            cart1.x - cart2.x,
            cart1.y - cart2.y,
            cart1.z - cart2.z,
        );
        const tolerance = Math.max(0.15, bond.bondLength * 0.1);
        return actualLength <= bond.bondLength + tolerance;
    };

    // Filter bonds to only include existing endpoints and omit periodic boundary
    // connections whose wrapped endpoints are no longer adjacent.
    const filteredBonds = finalBonds.filter(bond => {
        const atom1Present = finalAtomLabels.has(bond.atom1Id);
        const atom2IsExternal = bond.atom2SiteSymmetry && bond.atom2SiteSymmetry !== '.';
        return atom1Present &&
            (finalAtomLabels.has(bond.atom2Id) || atom2IsExternal) &&
            hasCompatibleDisplayedLength(bond);
    });

    // Filter H-bonds to only include those where donor and hydrogen exist
    // (acceptor may be outside the cell with non-identity symmetry)
    const filteredHBonds = finalHBonds.filter(hbond =>
        finalAtomLabels.has(hbond.donorAtomId) && finalAtomLabels.has(hbond.hydrogenAtomId),
    );

    // Fragment growth can temporarily join several translated molecules through
    // external bonds. Once invalid display bonds have been removed, the remaining
    // connectivity describes the individual displayed molecules. Centre each of
    // those components independently and collapse translated duplicates.
    // Centre according to the bonds that will actually remain in the returned
    // structure. H-bond metadata must not temporarily join otherwise disconnected
    // atoms/components: if reconciliation later removes that H-bond, such atoms
    // would be left outside the cell despite being standalone in the final model.
    const centringBonds = filteredBonds;
    const filteredStructure = new CrystalStructure(
        structure.cell,
        finalAtoms,
        centringBonds,
        filteredHBonds,
        structure.symmetry,
    );
    const atomIdMap = new Map();
    for (const group of filteredStructure.calculateConnectedGroups()) {
        const centre = getFragmentCentre(group.atoms).toArray();
        const offset = centre.map(value => Math.floor(value));
        for (const atom of group.atoms) {
            const oldId = atom.uniqueId;
            atom.position.x -= offset[0];
            atom.position.y -= offset[1];
            atom.position.z -= offset[2];
            if (atom.appliedSymmetry) {
                atom.appliedSymmetry.translation[0] -= offset[0];
                atom.appliedSymmetry.translation[1] -= offset[1];
                atom.appliedSymmetry.translation[2] -= offset[2];
                atom.appliedSymmetry._updateKey();
            }
            atomIdMap.set(oldId, atom.uniqueId);
        }
    }

    const centredAtoms = [];
    const centredPositionMap = new Map();
    const centredAtomIds = new Map();
    const duplicateAtomIds = new Map();
    for (const atom of finalAtoms) {
        const positionKey = getAtomPositionKey(atom);
        const existingId = centredAtomIds.get(atom.uniqueId) || centredPositionMap.get(positionKey);
        if (existingId) {
            duplicateAtomIds.set(atom.uniqueId, existingId);
        } else {
            centredPositionMap.set(positionKey, atom.uniqueId);
            centredAtomIds.set(atom.uniqueId, atom.uniqueId);
            centredAtoms.push(atom);
        }
    }
    for (const [oldId, translatedId] of atomIdMap) {
        atomIdMap.set(oldId, duplicateAtomIds.get(translatedId) || translatedId);
    }

    const centredBonds = [];
    const centredBondIds = new Set();
    for (const bond of filteredBonds) {
        const atom1Id = atomIdMap.get(bond.atom1Id) || bond.atom1Id;
        const atom2Id = atomIdMap.get(bond.atom2Id) || bond.atom2Id;
        if (atom1Id === atom2Id) {
            continue;
        }
        const bondId = createBondIdentifier(atom1Id, atom2Id);
        if (!centredBondIds.has(bondId)) {
            bond.atom1Id = atom1Id;
            bond.atom2Id = atom2Id;
            centredBonds.push(bond);
            centredBondIds.add(bondId);
        }
    }

    const centredHBonds = [];
    const centredHBondIds = new Set();
    for (const hbond of filteredHBonds) {
        hbond.donorAtomId = atomIdMap.get(hbond.donorAtomId) || hbond.donorAtomId;
        hbond.hydrogenAtomId = atomIdMap.get(hbond.hydrogenAtomId) || hbond.hydrogenAtomId;
        hbond.acceptorAtomId = atomIdMap.get(hbond.acceptorAtomId) || hbond.acceptorAtomId;
        const hbondId = createHBondIdentifier(
            hbond.donorAtomId,
            hbond.hydrogenAtomId,
            hbond.acceptorAtomId,
        );
        if (!centredHBondIds.has(hbondId)) {
            centredHBonds.push(hbond);
            centredHBondIds.add(hbondId);
        }
    }

    return new CrystalStructure(
        structure.cell,
        centredAtoms,
        centredBonds,
        centredHBonds,
        structure.symmetry,
    );
}
